-- Portals, commercial policies and per-brand order separation
alter table public.representadas add column if not exists logo_url text;
alter table public.representadas add column if not exists contact_email text;
alter table public.representadas add column if not exists contact_phone text;

create table if not exists public.commercial_policies (
  id uuid primary key default gen_random_uuid(),
  representada_id uuid not null references public.representadas(id) on delete cascade,
  name text not null default 'Política comercial vigente',
  min_order_value numeric(14,2),
  min_order_units integer,
  payment_terms text,
  freight_policy text,
  order_deadline_days integer,
  delivery_estimate_days integer,
  notes text,
  valid_from date not null default current_date,
  valid_until date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promotions (
  id uuid primary key default gen_random_uuid(),
  representada_id uuid not null references public.representadas(id) on delete cascade,
  title text not null,
  description text,
  starts_at timestamptz,
  ends_at timestamptz,
  rules jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  representada_id uuid not null references public.representadas(id) on delete restrict,
  representative_user_id uuid references auth.users(id),
  status text not null default 'rascunho',
  subtotal numeric(14,2) not null default 0,
  discount_total numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  payment_terms_snapshot text,
  freight_policy_snapshot text,
  min_order_value_snapshot numeric(14,2),
  notes text,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  quantity numeric(12,3) not null check(quantity>0),
  unit_price numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  line_total numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.portal_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null check(role in ('cliente','representada','representante','admin')),
  customer_id uuid references public.customers(id) on delete set null,
  representada_id uuid references public.representadas(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.portal_requests (
 id uuid primary key default gen_random_uuid(),
 user_id uuid not null references auth.users(id) on delete cascade,
 role text not null check(role in ('cliente','representada','representante','admin')),
 customer_id uuid references public.customers(id) on delete set null,
 representada_id uuid references public.representadas(id) on delete set null,
 request_type text not null default 'geral',
 title text not null,
 description text not null,
 status text not null default 'aberta',
 admin_response text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
