const cfg=window.BIASUZ_CONFIG||{}, statusEl=document.getElementById("loginStatus");
const sb=(cfg.supabaseUrl&&cfg.supabasePublishableKey)?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
let leads=[],customerPage=0;const pageSize=100;
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const digits=v=>String(v??"").replace(/\D/g,"");
function showApp(on){document.getElementById("loginView").classList.toggle("hidden",on);document.getElementById("appView").classList.toggle("hidden",!on)}
async function boot(){if(!sb){statusEl.textContent="Supabase não configurado.";return}const {data:{session}}=await sb.auth.getSession();if(session){showApp(true);await refreshAll()}else showApp(false)}
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));statusEl.textContent="Entrando...";const {error}=await sb.auth.signInWithPassword({email:d.email,password:d.password});if(error){statusEl.textContent=error.message;statusEl.className="form-status err";return}showApp(true);await refreshAll()});
document.getElementById("logout").onclick=async()=>{await sb.auth.signOut();showApp(false)};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tabview").forEach(x=>x.classList.add("hidden"));document.getElementById("tab-"+b.dataset.tab).classList.remove("hidden")});

async function counts(){
 const [a,b,c,d]=await Promise.all([
  sb.from("leads").select("*",{count:"exact",head:true}),
  sb.from("customers").select("*",{count:"exact",head:true}),
  sb.from("representadas").select("*",{count:"exact",head:true}),
  sb.from("products").select("*",{count:"exact",head:true})
 ]);
 document.getElementById("kLeads").textContent=a.count||0;document.getElementById("kCustomers").textContent=b.count||0;document.getElementById("kBrands").textContent=c.count||0;document.getElementById("kProducts").textContent=d.count||0;
}
async function loadLeads(){
 const {data,error}=await sb.from("leads").select("*").order("created_at",{ascending:false}).limit(500);if(error){document.getElementById("leadRows").innerHTML='<p class="form-status err">'+esc(error.message)+'</p>';return}leads=data||[];renderLeads()
}
function renderLeads(){const q=document.getElementById("leadSearch").value.toLowerCase(),uf=document.getElementById("leadState").value,seg=document.getElementById("leadSegment").value;const rows=leads.filter(x=>(!q||[x.name,x.company,x.phone,x.brand].join(" ").toLowerCase().includes(q))&&(!uf||x.state===uf)&&(!seg||x.segment===seg));document.getElementById("leadRows").innerHTML=rows.length?rows.map(x=>'<div class="row"><div><strong>'+esc(x.company)+'</strong><br><small>'+esc(x.name)+'</small></div><div>'+esc(x.phone)+'<br><small>'+esc(x.email||"")+'</small></div><div><strong>'+esc(x.state)+'</strong><br><small>'+esc(x.segment)+'</small></div><div>'+esc(x.brand||"—")+'</div><select data-lead-stage="'+x.id+'">'+["novo","contatado","qualificado","proposta","pedido","ganho","perdido"].map(s=>'<option '+(x.stage===s?"selected":"")+'>'+s+'</option>').join("")+'</select><button class="btn btn-small" data-lead-wa="'+x.id+'">WhatsApp</button></div>').join(""):'<p class="muted">Nenhum lead encontrado.</p>';document.querySelectorAll("[data-lead-stage]").forEach(el=>el.onchange=async()=>{await sb.from("leads").update({stage:el.value}).eq("id",el.dataset.leadStage);const x=leads.find(v=>v.id===el.dataset.leadStage);if(x)x.stage=el.value});document.querySelectorAll("[data-lead-wa]").forEach(el=>el.onclick=()=>{const x=leads.find(v=>v.id===el.dataset.leadWa);if(x)openWA(x.phone,"Olá "+x.name+", aqui é o Junior da Biasuz Representações. Estou entrando em contato sobre seu interesse em "+(x.brand||x.segment)+".")})}
function openWA(phone,msg){let n=digits(phone);if(!n)return;if(n.length<=11)n="55"+n;window.open("https://wa.me/"+n+"?text="+encodeURIComponent(msg),"_blank")}

async function loadCustomers(reset=false){
 if(reset)customerPage=0;const q=document.getElementById("customerSearch").value.trim(),uf=document.getElementById("customerState").value,stage=document.getElementById("customerStage").value;
 let req=sb.from("customers").select("*").order("legal_name").range(customerPage*pageSize,customerPage*pageSize+pageSize-1);
 if(uf)req=req.eq("state",uf);if(stage)req=req.eq("lifecycle_stage",stage);if(q)req=req.or("cnpj.ilike.%"+q+"%,legal_name.ilike.%"+q+"%,trade_name.ilike.%"+q+"%,city.ilike.%"+q+"%,phone1.ilike.%"+digits(q)+"%");
 const {data,error}=await req;if(error){document.getElementById("customerRows").innerHTML='<p class="form-status err">'+esc(error.message)+'</p>';return}
 const rows=data||[];document.getElementById("customerPage").textContent=String(customerPage+1);document.getElementById("customerRows").innerHTML=rows.length?rows.map(x=>'<div class="row"><div><strong>'+esc(x.trade_name||x.legal_name)+'</strong><br><small>'+esc(x.legal_name)+'</small></div><div>'+esc(x.phone1||"—")+'<br><small>'+esc(x.email||"")+'</small></div><div>'+esc(x.city||"—")+'<br><small>'+esc(x.state||"")+'</small></div><div><span class="badge">'+esc(x.company_size||"porte n/i")+'</span></div><select data-customer-stage="'+x.id+'"><option '+(x.lifecycle_stage==="prospect"?"selected":"")+'>prospect</option><option '+(x.lifecycle_stage==="cliente"?"selected":"")+'>cliente</option><option '+(x.lifecycle_stage==="inativo"?"selected":"")+'>inativo</option><option '+(x.lifecycle_stage==="descartado"?"selected":"")+'>descartado</option></select><button class="btn btn-small" data-customer-wa="'+x.id+'">WhatsApp</button></div>').join(""):'<p class="muted">Nenhum registro nesta página.</p>';
 document.querySelectorAll("[data-customer-stage]").forEach(el=>el.onchange=async()=>sb.from("customers").update({lifecycle_stage:el.value}).eq("id",el.dataset.customerStage));
 document.querySelectorAll("[data-customer-wa]").forEach(el=>el.onclick=()=>{const x=rows.find(v=>v.id===el.dataset.customerWa);if(x)openWA(x.phone1,"Olá, aqui é o Junior da Biasuz Representações. Posso apresentar nosso portfólio de marcas e condições comerciais para sua empresa?")});
}
async function loadCatalog(){
 const {data,error}=await sb.from("representadas").select("id,name,slug,segments,catalog_status,products_count,official_url").order("name");if(error)return;
 document.getElementById("brandRows").innerHTML=(data||[]).map(b=>'<div class="row catalog-row"><div><strong>'+esc(b.name)+'</strong><br><small>'+esc((b.segments||[]).join(" • "))+'</small></div><div><span class="badge">'+esc(b.catalog_status)+'</span></div><div>'+esc(b.products_count||0)+' produtos</div><div><a target="_blank" rel="noopener" href="'+esc(b.official_url)+'">Site oficial</a></div><a class="btn btn-small" target="_blank" href="./brand.html?slug='+encodeURIComponent(b.slug)+'">Catálogo</a></div>').join("");
}
async function refreshAll(){await Promise.all([counts(),loadLeads(),loadCustomers(true),loadCatalog()])}

function dateValue(v){if(v===null||v===undefined||v==="")return null;const s=String(v).trim();if(/^\d{2}\/\d{2}\/\d{4}$/.test(s)){const[d,m,y]=s.split("/");return y+"-"+m+"-"+d}if(/^\d{8}$/.test(s))return s.slice(0,4)+"-"+s.slice(4,6)+"-"+s.slice(6,8);return null}
function clean(v){const s=String(v??"").trim();return !s||s==="0"?null:s}
function mapRow(r){const cnpj=digits(r["CNPJ"]).padStart(14,"0");if(cnpj.length!==14)return null;return {source:"lista_petshop_bahia_julho_2026",source_id:clean(r["ID"]),cnpj,branch_type:clean(r["MATRIZ/FILIAL"]),legal_name:clean(r["RAZAO SOCIAL"])||"SEM RAZAO SOCIAL",trade_name:clean(r["NOME FANTASIA"]),registration_status:clean(r["SIT CADASTRAL"]),registration_status_date:dateValue(r["DATA SIT CADASTRAL"]),start_date:dateValue(r["DATA INICIO ATIVIDADE"]),cnae_code:clean(r["CNAE CODIGO"]),cnae_description:clean(r["CNAE FISCAL"]),street_type:clean(r["DESC TIPO LOGRADOURO"]),street:clean(r["LOGRADOURO"]),number:clean(r["NUMERO"]),complement:clean(r["COMPLEMENTO"]),district:clean(r["BAIRRO"]),zip_code:digits(r["CEP"]).padStart(8,"0")||null,state:clean(r["UF"]),city_code:clean(r["COD MUNICIPIO"]),city:clean(r["MUNICIPIO"]),phone1:digits(r["DDD TELEFONE 1"])||null,phone1_is_mobile:["1","S","SIM","TRUE"].includes(String(r["TELEFONE1_CELULAR?"]??"").toUpperCase()),phone2:digits(r["DDD TELEFONE 2"])||null,phone2_is_mobile:["1","S","SIM","TRUE"].includes(String(r["TELEFONE2_CELULAR?"]??"").toUpperCase()),email:clean(r["CORREIO ELETRONICO"]),responsible_qualification:clean(r["QUALIF RESPONSAVEL"]),share_capital:Number(String(r["CAPITAL SOCIAL EMPRESA"]??"0").replace(",", "."))||null,company_size:clean(r["PORTE EMPRESA"]),simples_option:clean(r["OPCAO SIMPLES"]),mei_option:clean(r["OPCAO MEI"]),partners:clean(r["SOCIOS"]),secondary_cnaes:clean(r["CNAES SECUNDARIOS"]),segment:"Pet",lifecycle_stage:"prospect",commercial_owner:"Junior"}}
document.getElementById("importCsv").onclick=()=>{const file=document.getElementById("csvFile").files[0],status=document.getElementById("importStatus"),bar=document.getElementById("importBar");if(!file){status.textContent="Selecione o arquivo CSV.";return}status.textContent="Lendo arquivo...";Papa.parse(file,{header:true,skipEmptyLines:true,complete:async res=>{try{const rows=res.data.map(mapRow).filter(Boolean);let done=0;for(let i=0;i<rows.length;i+=250){const batch=rows.slice(i,i+250);const {error}=await sb.from("customers").upsert(batch,{onConflict:"cnpj"});if(error)throw error;done+=batch.length;bar.style.width=Math.round(done/rows.length*100)+"%";status.textContent=done+" / "+rows.length+" registros importados"}status.className="form-status ok";status.textContent="Importação concluída: "+done+" registros.";await counts();await loadCustomers(true)}catch(e){status.className="form-status err";status.textContent="Erro na importação: "+e.message}}})};

["leadSearch","leadState","leadSegment"].forEach(id=>document.getElementById(id).addEventListener(id==="leadSearch"?"input":"change",renderLeads));
document.getElementById("reloadLeads").onclick=loadLeads;document.getElementById("reloadCustomers").onclick=()=>loadCustomers(true);document.getElementById("prevCustomers").onclick=()=>{if(customerPage>0){customerPage--;loadCustomers()}};document.getElementById("nextCustomers").onclick=()=>{customerPage++;loadCustomers()};boot();