const cfg=window.BIASUZ_CONFIG||{}, statusEl=document.getElementById("loginStatus");
if(!cfg.supabasePublishableKey){statusEl.textContent="Configuração do Supabase pendente.";statusEl.className="form-status err"}
const sb=(cfg.supabaseUrl&&cfg.supabasePublishableKey)?window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey):null;
let all=[];
const login=document.getElementById("loginView"),app=document.getElementById("appView");
function showApp(on){login.classList.toggle("hidden",on);app.classList.toggle("hidden",!on)}
async function boot(){if(!sb)return;const {data:{session}}=await sb.auth.getSession();if(session){showApp(true);load()}else showApp(false)}
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();if(!sb)return;const d=Object.fromEntries(new FormData(e.currentTarget));statusEl.textContent="Entrando...";const {error}=await sb.auth.signInWithPassword({email:d.email,password:d.password});if(error){statusEl.textContent=error.message;statusEl.className="form-status err";return}showApp(true);load()});
document.getElementById("logout").onclick=async()=>{await sb.auth.signOut();showApp(false)};
async function load(){const {data,error}=await sb.from("leads").select("*").order("created_at",{ascending:false});if(error){document.getElementById("leads").innerHTML='<p class="form-status err">'+error.message+'</p>';return}all=data||[];render()}
function render(){const q=document.getElementById("search").value.toLowerCase(),uf=document.getElementById("stateFilter").value,seg=document.getElementById("segmentFilter").value;const rows=all.filter(x=>(!q||[x.name,x.company,x.phone,x.brand].join(" ").toLowerCase().includes(q))&&(!uf||x.state===uf)&&(!seg||x.segment===seg));document.getElementById("kTotal").textContent=all.length;document.getElementById("kNew").textContent=all.filter(x=>x.stage==="novo").length;document.getElementById("kProposal").textContent=all.filter(x=>x.stage==="proposta").length;document.getElementById("kWon").textContent=all.filter(x=>x.stage==="ganho").length;document.getElementById("leads").innerHTML=rows.length?rows.map(x=>'<div class="lead-row"><div><strong>'+esc(x.company)+'</strong><br><small>'+esc(x.name)+'</small></div><div>'+esc(x.phone)+'<br><small>'+esc(x.email||"")+'</small></div><div><strong>'+x.state+'</strong><br><small>'+esc(x.segment)+'</small></div><div>'+esc(x.brand||"—")+'</div><select data-stage="'+x.id+'">'+["novo","contatado","qualificado","proposta","pedido","ganho","perdido"].map(s=>'<option value="'+s+'" '+(x.stage===s?"selected":"")+'>'+s+'</option>').join("")+'</select><button class="btn btn-small" data-wa="'+x.id+'">WhatsApp</button></div>').join(""):'<p class="muted">Nenhum lead encontrado.</p>';document.querySelectorAll("[data-stage]").forEach(el=>el.onchange=()=>stage(el.dataset.stage,el.value));document.querySelectorAll("[data-wa]").forEach(el=>el.onclick=()=>openWA(el.dataset.wa))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function stage(id,value){const {error}=await sb.from("leads").update({stage:value}).eq("id",id);if(!error){const x=all.find(v=>v.id===id);if(x)x.stage=value;render()}}
function openWA(id){const x=all.find(v=>v.id===id);if(!x)return;const n=(x.phone||"").replace(/\D/g,"");window.open("https://wa.me/55"+n+"?text="+encodeURIComponent("Olá "+x.name+", aqui é o Junior da Biasuz Representações. Estou entrando em contato sobre seu interesse em "+(x.brand||x.segment)+"."),"_blank")}
["search","stateFilter","segmentFilter"].forEach(id=>document.getElementById(id).addEventListener(id==="search"?"input":"change",render));boot();