const cfg=window.BIASUZ_CONFIG||{},sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey),id=new URLSearchParams(location.search).get("id");
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=v=>"R$ "+Number(v||0).toLocaleString("pt-BR",{minimumFractionDigits:2});
let customer=null,sellers=[],regions=[];
function status(id,msg,kind=""){const e=document.getElementById(id);e.className="status "+kind;e.textContent=msg}
async function auth(){const {data:{user}}=await sb.auth.getUser();if(!user||user.app_metadata?.role!=="admin"){location.href="./admin.html";return false}return true}
async function boot(){if(!id||!await auth())return;await Promise.all([loadBase(),loadInteractions(),loadOrders()])}
async function loadBase(){
 const [c,s,r]=await Promise.all([sb.from("customers").select("*").eq("id",id).single(),sb.from("salespeople").select("*").eq("active",true).order("name"),sb.from("sales_regions").select("*").eq("active",true).order("code")]);
 if(c.error)throw c.error;customer=c.data;sellers=s.data||[];regions=r.data||[];
 document.getElementById("title").textContent=customer.trade_name||customer.legal_name;document.getElementById("subtitle").textContent=customer.legal_name+" · "+(customer.city||"")+" / "+(customer.state||"");
 document.getElementById("customerInfo").innerHTML=[
  ["CNPJ",customer.cnpj],["Segmento",customer.segment],["Situação",customer.registration_status||"—"],["Telefone",customer.phone1||"—"],["E-mail",customer.email||"—"],["Endereço",[customer.street,customer.number,customer.district,customer.city,customer.state].filter(Boolean).join(", ")]
 ].map(x=>'<div class="box"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>').join("");
 const f=document.getElementById("customerForm");f.elements.lifecycle_stage.value=customer.lifecycle_stage||"prospect";f.elements.notes.value=customer.notes||"";if(customer.next_action_at)f.elements.next_action_at.value=new Date(customer.next_action_at).toISOString().slice(0,16);
 document.getElementById("salespersonSelect").innerHTML='<option value="">Sem vendedor</option>'+sellers.map(x=>'<option value="'+x.id+'" '+(x.id===customer.salesperson_id?"selected":"")+'>'+esc(x.name)+'</option>').join("");
 document.getElementById("regionSelect").innerHTML='<option value="">Sem região</option>'+regions.map(x=>'<option value="'+x.id+'" '+(x.id===customer.sales_region_id?"selected":"")+'>'+esc(x.code+" · "+x.name)+'</option>').join("");
 const digits=String(customer.phone1||"").replace(/\D/g,"");document.getElementById("waAction").href=digits?("https://wa.me/"+(digits.startsWith("55")?digits:"55"+digits)+"?text="+encodeURIComponent("Olá, aqui é a Biasuz Representações.")):"#";
 document.getElementById("emailAction").href=customer.email?"mailto:"+encodeURIComponent(customer.email):"#";
}
document.getElementById("customerForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));status("customerStatus","Salvando...");const row={lifecycle_stage:d.lifecycle_stage,salesperson_id:d.salesperson_id||null,sales_region_id:d.sales_region_id||null,next_action_at:d.next_action_at?new Date(d.next_action_at).toISOString():null,notes:d.notes||null,commercial_owner:sellers.find(x=>x.id===d.salesperson_id)?.name||customer.commercial_owner,updated_at:new Date().toISOString()};const {error}=await sb.from("customers").update(row).eq("id",id);if(error)return status("customerStatus",error.message,"err");status("customerStatus","Cadastro atualizado.","ok");await loadBase()};
async function loadInteractions(){const {data,error}=await sb.from("interactions").select("*").eq("customer_id",id).order("created_at",{ascending:false}).limit(100);const box=document.getElementById("interactionRows");box.innerHTML=error?'<p class="status err">'+esc(error.message)+'</p>':(data||[]).length?(data||[]).map(x=>'<div class="item"><strong>'+esc(x.channel)+' · '+(x.direction==="inbound"?"Cliente → Biasuz":"Biasuz → Cliente")+'</strong><small> · '+new Date(x.created_at).toLocaleString("pt-BR")+'</small><p>'+esc(x.summary)+'</p></div>').join(""):'<p class="muted">Nenhuma interação registrada.</p>'}
document.getElementById("interactionForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),{data:{user}}=await sb.auth.getUser();status("interactionStatus","Registrando...");const {error}=await sb.from("interactions").insert({customer_id:id,channel:d.channel,direction:d.direction,summary:d.summary,created_by:user.id});if(error)return status("interactionStatus",error.message,"err");await sb.from("customers").update({last_contact_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);e.currentTarget.reset();status("interactionStatus","Interação registrada.","ok");loadInteractions()};
async function loadOrders(){const {data,error}=await sb.from("orders").select("order_number,status,total,created_at,representadas(name)").eq("customer_id",id).order("created_at",{ascending:false}).limit(100);const box=document.getElementById("orderRows");box.innerHTML=error?'<p class="status err">'+esc(error.message)+'</p>':(data||[]).length?(data||[]).map(o=>'<div class="item"><strong>Pedido #'+esc(o.order_number)+' · '+esc(o.representadas?.name||"")+'</strong><small> · '+new Date(o.created_at).toLocaleDateString("pt-BR")+'</small><p>'+esc(o.status)+' · '+money(o.total)+'</p></div>').join(""):'<p class="muted">Nenhum pedido deste cliente.</p>'}
boot().catch(e=>{document.body.insertAdjacentHTML("afterbegin",'<div style="background:#602020;color:#fff;padding:12px">Erro: '+esc(e.message)+'</div>')});